receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s

exporters:
  lofi:
    backend_url: http://lofi-backend:9292
    api_key: ${env:LOFI_API_KEY}
    # exclude_packages:
    #   - com.acme.api.controller.admin.*
    #   - com.acme.adaptor.ops.*

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [lofi]
