plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    api project(':lofi-core')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation "org.xerial:sqlite-jdbc:${sqliteJdbcVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
